spring.application.name=slack-consumer
spring.config.import=optional:file:./.env[.properties]

server.port=8084

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=slack-group
kafka.topic.slack=slack.notification


slack.webhook-url=${SLACK_WEBHOOK:}